apiVersion: audit.k8s.io/v1beta1
kind: Policy
omitStages:
  - "RequestReceived"
rules:
- level: RequestResponse
  resources:
  - group: "" # core
    resources: ["pods", "secrets"]
  - group: "extensions"
    resources: ["deployments"]
